# BASICS OF PYTHON

## 1. SPLIT THE STRING

In [ ]:
str = "HEY!! GOOD MORNING"
print(str.split())

['HEY!!', 'GOOD', 'MORNING']


## 2. USE .format() TO PRINT THE FOLLOWING STRING.

In [ ]:
mailid = "abc@gmail.com"
password = "asdf@123"
str = "Your username and password are {} and {}"
print(str.format(mailid,password))

Your username and password are abc@gmail.com and asdf@123


## 3. IN THIS NEST DICTIONARY GRAB THE WORD "HELLO"

In [ ]:
S = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(S['k1'][3]['tricky'][3]['target'][3])

hello


# NUMPY LIB

In [ ]:
import numpy as n

## 4. CREATE AN ARRAY OF 10 ZEROS AND 10 FIVES?

In [ ]:
arr1 = n.zeros(10)
arr2 = n.ones(10)*5
print(arr1)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. CREATE AN ARRAY OF ALL THE EVEN INTEGERS FROM 50 TO 70.

In [ ]:
arr = n.arange(50,70,2)
print(arr)

[50 52 54 56 58 60 62 64 66 68]


## 6. CREATE A 3*3 WITH VALUES RANGING FROM 0 TO 8

In [ ]:
arr = n.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. CONCATENATE A and B ARRAYS


In [ ]:
A = n.array([1, 2, 3])
B = n.array([4, 5, 6])
print(n.concatenate((A,B)))

[1 2 3 4 5 6]


# PANDAS LIB

## 8. CREATE A DATAFRAME WITH 3 ROWS AND 2 COLUMNS.

In [ ]:
import pandas as p
m = n.array([[8,5],[1,2],[4,7]])
print(m)
data_frame = p.DataFrame(m)
print(data_frame)

[[8 5]
 [1 2]
 [4 7]]
   0  1
0  8  5
1  1  2
2  4  7


## 9. GENERATE THE SERIES OF DATES FROM 1ST JAN,2023 TO 10TH FEB,2023.

In [ ]:
start_time = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
end_time = datetime.datetime.strptime("10-02-2023", "%d-%m-%Y")
date_series = p.date_range(start_time, end_time)
print(date_series.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


## 10. CREATE 2D LIST TO DATAFRAME

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
data_frame = p.DataFrame(lists)
print(data_frame)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
